### ISSUE TITLE
document flashrom chip configs

### ISSUE THREAD

**Issue by merge** [merge/coreboot-x230#15]
4MB chip:
* `MX25L3206E` works for me so far

8MB chip:
* `MX25L6406E/MX25L6408E` seems to [work](https://github.com/mfc/flashing-docs/blob/master/walkthrough%20for%20flashing%20heads%20on%20an%20x230.md#neutering-me) 
* `MX25L3206E/MX25L3208E` works for me too

**Comment by tjburrows** [comment]
For my 4 MB chip, I also use the MX25L3206E/MX25L3208E setting.  However, my 8 MB is an Eon EN25QH64, according to flashrom.
