### ISSUE TITLE
CBFS size should be 4MB, not 1MB

### ISSUE THREAD

**Issue by nemanjan00** [merge/coreboot-x230#5]

**Comment by nemanjan00** [comment]
BTW, you can make internal flashing work. 

I made it work on my laptop...

**Comment by merge** [comment]
I know. I do so on an X220, but one X230 once completely died after I flashed internally. It was strange and I don't want to go into details but I find flashing externally, with slow speed the safest way to go.

**Comment by nemanjan00** [comment]
I fried x230 with external flashing, so I prefer internal...

Noone can figure out what happened to my either
