### ISSUE TITLE
Settings payload

### ISSUE THREAD

**Issue by nemanjan00** [merge/coreboot-x230#6]
https://www.reddit.com/r/thinkpad/comments/68ez34/thinkpad_x230_coreboot_button_swap/dgxy45b/

**Comment by nemanjan00** [comment]
I had to clear CMOS after these changes. 

Just enable CMOS settings loading and we can set settings using nvramtool...

**Comment by merge** [comment]
what config option exactly do you mean to enable?

**Comment by nemanjan00** [comment]
Load settings from CMOS, or something like that, I can not remmember. Will
take a look when I get home

**Comment by nemanjan00** [comment]
Inside general: 
![Uploading Screenshot from 2018-01-25 16-48-43.png…]()

**Comment by merge** [comment]
Thanks for your help! I plan to do a THANKS file. If you want that, give me your name and email address, and I'd be happy to include you. so, thanks.

**Comment by nemanjan00** [comment]
Thank you for making this happen. :)

I do not think I could configure my build environment without your config. 

BTW, how about making IRC channel so we can discuss what improvements we can make? 

I have a few ideas...

**Comment by merge** [comment]
I think setting anything more than a repo up would be overkill. Remember we simply use coreboot here, and even that only for creating a valid image for 4MB of the 12.

If you have an idea, why not open an issue here or post it on the coreboot list?
