### ISSUE TITLE
SHA1 checksum of 0.0.2 release failed

### ISSUE THREAD

**Issue by apraile** [merge/coreboot-x230#8]
There is a minor mistake in `x230_i5_coreboot_seabios_533ea7adb5_top.rom.sha1` file:

`sed 's/x230_coreboot_seabios_533ea7adb5_top.rom/x230_i5_coreboot_seabios_533ea7adb5_top.rom/'`

**Comment by merge** [comment]
Doing a i5-only version in the first place was totally unnecessary, but it works and we have it now, so the checksum should be correct too. Thanks for reporting.
